replaced err = {} in catch
SushiBtw/discord-music-player pull request #107
Opened 2021-04-07 16:48 UTC by SpeckyYT

I caused this "Unexpected token =" error, sorry

2021-04-08 07:06 UTC, SushiBtw requested changes
pls pls

2021-04-08 07:06 UTC, SushiBtw commented on src/Player.js
> +            this.emit('error', err ? err.message : err, message);
We should use `err.message ?? err`, as if err is a string it will still log `undefined`.

2021-04-08 07:06 UTC, SushiBtw commented on src/Player.js
> +            this.emit('error', err ? err.message : err, message);
We should use `err.message ?? err`, as if err is a string it will still log `undefined`.

2021-04-09 12:03 UTC, SpeckyYT commented
fixed

2021-04-09 12:04 UTC, SushiBtw approved these changes

2021-04-09 12:05 UTC, merged