added getVolume
SushiBtw/discord-music-player pull request #64
Opened 2021-02-04 16:39 UTC by SpeckyYT

2021-02-18 16:21 UTC, SpeckyYT commented
I'll update the queues anyways

2021-02-22 11:08 UTC, SushiBtw commented on src/Player.js
> +        let queue = this.getQueue(guildID);
Please change to `this.queues.get()` ty <3

2021-02-22 11:09 UTC, SushiBtw requested changes
change to maping, please!

2021-02-22 12:12 UTC, SushiBtw reviewed
thanks!

2021-02-22 12:12 UTC, SushiBtw approved these changes

2021-02-22 12:13 UTC, merged